# Azure DevOps Pipeline for Playwright Cucumber Tests

trigger:
  branches:
    include:
      - main
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  BROWSER: 'chromium'

stages:
- stage: Smoke
  jobs:
  - job: Chromium
    displayName: 'Smoke Suite - Chromium'
    steps:
    - checkout: self
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'
    - script: npm install
      displayName: 'Install dependencies'
    - script: npx playwright install --with-deps
      displayName: 'Install Playwright browsers'
    - script: npm run smoke
      displayName: 'Run Cucumber Smoke Suite (Chromium)'
    - script: npm run report
      displayName: 'Generate Cucumber HTML Report'
    - publish: reports/cucumber-report.html
      artifact: cucumber-html-report-chromium

  - job: Firefox
    displayName: 'Smoke Suite - Firefox'
    variables:
      BROWSER: 'firefox'
    steps:
    - checkout: self
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'
    - script: npm install
      displayName: 'Install dependencies'
    - script: npx playwright install --with-deps
      displayName: 'Install Playwright browsers'
    - script: npm run smoke
      displayName: 'Run Cucumber Smoke Suite (Firefox)'
    - script: npm run report
      displayName: 'Generate Cucumber HTML Report'
    - publish: reports/cucumber-report.html
      artifact: cucumber-html-report-firefox

  - job: WebKit
    displayName: 'Smoke Suite - WebKit'
    variables:
      BROWSER: 'webkit'
    steps:
    - checkout: self
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'
    - script: npm install
      displayName: 'Install dependencies'
    - script: npx playwright install --with-deps
      displayName: 'Install Playwright browsers'
    - script: npm run smoke
      displayName: 'Run Cucumber Smoke Suite (WebKit)'
    - script: npm run report
      displayName: 'Generate Cucumber HTML Report'
    - publish: reports/cucumber-report.html
      artifact: cucumber-html-report-webkit
